-- Supabase Dashboard > SQL Editor で実行してください(MCP接続が切れているため、このセッションでは
-- 直接適用できていません)。
--
-- 「アメリカの大学に通うアメリカ人学生がこのアプリをそのまま使う」ケースに対応するため、
-- 主要な米国大学とその公式.eduドメインを追加する。これまでカーネギーメロン大学(andrew.cmu.edu)
-- のみだったため、大学メールアドレスでサインアップできるアメリカの大学が実質1校しかなかった。
--
-- prefectureにはUnitedStatesの州名(英語表記。Matching App/Profile.swiftのusStates定数と
-- 揃えている)を入れており、居住地(州)で大学を絞り込む機能と連動する。
--
-- 実在しないドメインを誤って登録すると、その大学の学生が一切サインアップできなくなるため、
-- 追加後に実際の学生から「登録できない」との報告があれば、domain列を実際のドメインに
-- 修正してください(university_domain_fixes.sqlと同じ要領)。

insert into public.universities (name, domain, country, prefecture)
select v.name, v.domain, 'アメリカ', v.state
from (values
  -- Ivy League + 主要私立
  ('Harvard University', 'harvard.edu', 'Massachusetts'),
  ('Yale University', 'yale.edu', 'Connecticut'),
  ('Princeton University', 'princeton.edu', 'New Jersey'),
  ('Columbia University', 'columbia.edu', 'New York'),
  ('University of Pennsylvania', 'upenn.edu', 'Pennsylvania'),
  ('Cornell University', 'cornell.edu', 'New York'),
  ('Brown University', 'brown.edu', 'Rhode Island'),
  ('Dartmouth College', 'dartmouth.edu', 'New Hampshire'),
  ('Massachusetts Institute of Technology', 'mit.edu', 'Massachusetts'),
  ('Stanford University', 'stanford.edu', 'California'),
  ('University of Chicago', 'uchicago.edu', 'Illinois'),
  ('Johns Hopkins University', 'jhu.edu', 'Maryland'),
  ('Northwestern University', 'northwestern.edu', 'Illinois'),
  ('Duke University', 'duke.edu', 'North Carolina'),
  ('Vanderbilt University', 'vanderbilt.edu', 'Tennessee'),
  ('Rice University', 'rice.edu', 'Texas'),
  ('University of Notre Dame', 'nd.edu', 'Indiana'),
  ('Georgetown University', 'georgetown.edu', 'District of Columbia'),
  ('Carnegie Mellon University', 'cmu.edu', 'Pennsylvania'),
  ('Emory University', 'emory.edu', 'Georgia'),
  ('Tufts University', 'tufts.edu', 'Massachusetts'),
  ('Boston University', 'bu.edu', 'Massachusetts'),
  ('Boston College', 'bc.edu', 'Massachusetts'),
  ('Northeastern University', 'northeastern.edu', 'Massachusetts'),
  ('New York University', 'nyu.edu', 'New York'),
  ('Syracuse University', 'syr.edu', 'New York'),
  ('University of Rochester', 'rochester.edu', 'New York'),
  ('Case Western Reserve University', 'case.edu', 'Ohio'),
  ('Tulane University', 'tulane.edu', 'Louisiana'),
  ('Washington University in St. Louis', 'wustl.edu', 'Missouri'),
  ('Villanova University', 'villanova.edu', 'Pennsylvania'),
  ('Temple University', 'temple.edu', 'Pennsylvania'),
  ('University of Pittsburgh', 'pitt.edu', 'Pennsylvania'),
  ('University of Miami', 'miami.edu', 'Florida'),
  ('Southern Methodist University', 'smu.edu', 'Texas'),
  ('Texas Christian University', 'tcu.edu', 'Texas'),
  ('Baylor University', 'baylor.edu', 'Texas'),
  ('Brigham Young University', 'byu.edu', 'Utah'),
  ('DePaul University', 'depaul.edu', 'Illinois'),
  ('Loyola University Chicago', 'luc.edu', 'Illinois'),
  ('Marquette University', 'marquette.edu', 'Wisconsin'),

  -- 主要州立大学(旗艦校)
  ('University of California, Berkeley', 'berkeley.edu', 'California'),
  ('University of California, Los Angeles', 'ucla.edu', 'California'),
  ('University of California, San Diego', 'ucsd.edu', 'California'),
  ('University of California, Irvine', 'uci.edu', 'California'),
  ('University of California, Davis', 'ucdavis.edu', 'California'),
  ('University of California, Santa Barbara', 'ucsb.edu', 'California'),
  ('University of California, Santa Cruz', 'ucsc.edu', 'California'),
  ('University of California, Riverside', 'ucr.edu', 'California'),
  ('University of Southern California', 'usc.edu', 'California'),
  ('San Diego State University', 'sdsu.edu', 'California'),
  ('San Jose State University', 'sjsu.edu', 'California'),
  ('California Polytechnic State University', 'calpoly.edu', 'California'),
  ('University of Michigan', 'umich.edu', 'Michigan'),
  ('Michigan State University', 'msu.edu', 'Michigan'),
  ('Wayne State University', 'wayne.edu', 'Michigan'),
  ('University of Wisconsin-Madison', 'wisc.edu', 'Wisconsin'),
  ('University of Wisconsin-Milwaukee', 'uwm.edu', 'Wisconsin'),
  ('University of Illinois Urbana-Champaign', 'illinois.edu', 'Illinois'),
  ('University of Minnesota', 'umn.edu', 'Minnesota'),
  ('Ohio State University', 'osu.edu', 'Ohio'),
  ('Pennsylvania State University', 'psu.edu', 'Pennsylvania'),
  ('Rutgers University', 'rutgers.edu', 'New Jersey'),
  ('University of Maryland', 'umd.edu', 'Maryland'),
  ('University of North Carolina at Chapel Hill', 'unc.edu', 'North Carolina'),
  ('North Carolina State University', 'ncsu.edu', 'North Carolina'),
  ('University of Virginia', 'virginia.edu', 'Virginia'),
  ('Virginia Tech', 'vt.edu', 'Virginia'),
  ('University of Texas at Austin', 'utexas.edu', 'Texas'),
  ('Texas A&M University', 'tamu.edu', 'Texas'),
  ('Texas Tech University', 'ttu.edu', 'Texas'),
  ('University of Houston', 'uh.edu', 'Texas'),
  ('Georgia Institute of Technology', 'gatech.edu', 'Georgia'),
  ('University of Georgia', 'uga.edu', 'Georgia'),
  ('University of Florida', 'ufl.edu', 'Florida'),
  ('Florida State University', 'fsu.edu', 'Florida'),
  ('University of Central Florida', 'ucf.edu', 'Florida'),
  ('Florida International University', 'fiu.edu', 'Florida'),
  ('Arizona State University', 'asu.edu', 'Arizona'),
  ('University of Arizona', 'arizona.edu', 'Arizona'),
  ('University of Colorado Boulder', 'colorado.edu', 'Colorado'),
  ('Colorado State University', 'colostate.edu', 'Colorado'),
  ('University of Washington', 'washington.edu', 'Washington'),
  ('Washington State University', 'wsu.edu', 'Washington'),
  ('University of Oregon', 'uoregon.edu', 'Oregon'),
  ('Oregon State University', 'oregonstate.edu', 'Oregon'),
  ('Purdue University', 'purdue.edu', 'Indiana'),
  ('Indiana University Bloomington', 'iu.edu', 'Indiana'),
  ('University of Iowa', 'uiowa.edu', 'Iowa'),
  ('Iowa State University', 'iastate.edu', 'Iowa'),
  ('University of Nebraska-Lincoln', 'unl.edu', 'Nebraska'),
  ('University of Kansas', 'ku.edu', 'Kansas'),
  ('Kansas State University', 'k-state.edu', 'Kansas'),
  ('University of Missouri', 'missouri.edu', 'Missouri'),
  ('University of Oklahoma', 'ou.edu', 'Oklahoma'),
  ('Oklahoma State University', 'okstate.edu', 'Oklahoma'),
  ('University of Utah', 'utah.edu', 'Utah'),
  ('University of Nevada, Las Vegas', 'unlv.edu', 'Nevada'),
  ('University of Nevada, Reno', 'unr.edu', 'Nevada'),
  ('University of New Mexico', 'unm.edu', 'New Mexico'),
  ('Louisiana State University', 'lsu.edu', 'Louisiana'),
  ('University of Alabama', 'ua.edu', 'Alabama'),
  ('Auburn University', 'auburn.edu', 'Alabama'),
  ('University of Mississippi', 'olemiss.edu', 'Mississippi'),
  ('Mississippi State University', 'msstate.edu', 'Mississippi'),
  ('University of Tennessee', 'utk.edu', 'Tennessee'),
  ('University of Kentucky', 'uky.edu', 'Kentucky'),
  ('University of South Carolina', 'sc.edu', 'South Carolina'),
  ('Clemson University', 'clemson.edu', 'South Carolina'),
  ('West Virginia University', 'wvu.edu', 'West Virginia'),
  ('University of Connecticut', 'uconn.edu', 'Connecticut'),
  ('University of Massachusetts Amherst', 'umass.edu', 'Massachusetts'),
  ('Stony Brook University', 'stonybrook.edu', 'New York'),
  ('University at Buffalo', 'buffalo.edu', 'New York'),
  ('Binghamton University', 'binghamton.edu', 'New York'),
  ('University at Albany', 'albany.edu', 'New York'),
  ('University of Delaware', 'udel.edu', 'Delaware'),
  ('University of Vermont', 'uvm.edu', 'Vermont'),
  ('University of Maine', 'maine.edu', 'Maine'),
  ('University of Hawaii at Manoa', 'hawaii.edu', 'Hawaii'),
  ('University of Idaho', 'uidaho.edu', 'Idaho'),
  ('Boise State University', 'boisestate.edu', 'Idaho'),
  ('Montana State University', 'montana.edu', 'Montana'),
  ('University of Montana', 'umt.edu', 'Montana'),
  ('University of Wyoming', 'uwyo.edu', 'Wyoming'),
  ('North Dakota State University', 'ndsu.edu', 'North Dakota'),
  ('University of North Dakota', 'und.edu', 'North Dakota'),
  ('South Dakota State University', 'sdstate.edu', 'South Dakota'),
  ('University of Arkansas', 'uark.edu', 'Arkansas'),
  ('George Washington University', 'gwu.edu', 'District of Columbia'),
  ('American University', 'american.edu', 'District of Columbia'),
  ('University of San Francisco', 'usfca.edu', 'California'),
  ('Santa Clara University', 'scu.edu', 'California'),
  ('Loyola Marymount University', 'lmu.edu', 'California'),
  ('Pepperdine University', 'pepperdine.edu', 'California')
) as v(name, domain, state)
where not exists (
  select 1 from public.universities u where u.domain = v.domain
);
